In [4]:
import pandas as pd
import requests
import time

In [ ]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [ ]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [ ]:
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,18.433,8.7,2763
1,724089,Gabriel's Inferno Part II,Professor Gabriel Emerson finally learns the t...,2020-07-31,8.439,8.7,1223
2,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,65.570,8.7,18637
3,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,63.277,8.7,14052
4,761053,Gabriel's Inferno Part III,The final part of the film adaption of the ero...,2020-11-19,26.691,8.7,773

In [2]:
df = pd.DataFrame()

In [3]:
df

Empty DataFrame
Columns: []
Index: []

In [5]:
for i in range(1,400):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = pd.concat([df, temp_df], ignore_index=True)  # Here i used time sleep because too frequent api hit cause problem  and i have total page size 519 so i can maximise my row
    time.sleep(0.25)

In [7]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,28.6613,8.713,28947
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,28.7339,8.686,21878
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,17.1534,8.571,13218
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,13.0232,8.566,16733
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,12.2075,8.548,9424
...,...,...,...,...,...,...,...
7975,1051896,Arcadian,"In the near future, on a decimated Earth, Paul...",2024-04-12,6.7296,6.069,742
7976,437670,Suck Me Shakespeer 3,A bank robber becomes a teacher after being re...,2017-10-26,3.1888,6.069,474
7977,383709,Wonderstruck,The story of a young boy in the Midwest is tol...,2017-10-13,2.9993,6.100,419
7978,119283,Parker,A thief with a unique code of professional eth...,2013-01-23,6.0648,6.069,3146
7979,9085,Harlem Nights,'Sugar' Ray is the owner of an illegal casino ...,1989-11-17,1.5446,6.069,328

In [6]:
df.shape

(7980, 7)

In [8]:
df.to_csv('movies.csv')